// import type { Metadata } from "next";
// import { Public_Sans } from "next/font/google";
// import { cookies, headers } from "next/headers";
// import { redirect } from "next/navigation";
// import apiServer from "helper/server_api";

// // components
// import ClientWrapper from "/components/common/ClientWrapper";
// import Sidebar from "/layouts/Sidebar";
// import Header from "/layouts/header/Header";

// // styles
// import "swiper/css";
// import "swiper/css/navigation";
// import "swiper/css/pagination";
// import "swiper/css/scrollbar";
// import "/styles/theme.scss";

// const publicSans = Public_Sans({
//   variable: "--font-public-sans",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Dashboard",
//   description: "Next.js Role Based Dashboard",
// };

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   // const cookieStore = cookies();
//   // const token = (await cookieStore).get("accessToken")?.value;

//   // if (!token) {
//   //   redirect("http://localhost:3002/login");
//   // }

//   // ✅ fetch user
//   // let me: any;
//   // try {
//   //   const res = await apiServer.get("/auth/me", {
//   //     headers: { Authorization: `Bearer ${token}` },
//   //   });
//   //   me = res.data;
//   // } catch (err) {
//   //   console.error("❌ Failed to fetch /auth/me", err);
//   //   redirect("http://localhost:3002/login");
//   // }

//   // // ✅ extract role from URL
//   // const pathname = (await headers()).get("x-invoke-path") || "/";
//   // const roleFromUrl = pathname.split("/")[1]; // e.g. "SuperAdmin"

//   // // ✅ guard: user ke paas role hai?
//   // if (
//   //   !me.roles?.some(
//   //     (r: string) => r.toLowerCase() === roleFromUrl.toLowerCase()
//   //   )
//   // ) {
//   //   redirect("http://localhost:3002/choose-role");
//   // }

//   return (
//     <html lang="en" className="expanded">
//       <body className={`${publicSans.variable}`}>
//         <ClientWrapper user={me} token={token} >
//           {/* <div className="d-flex">
//             {/* Sidebar */}
//             <div className="d-none d-lg-block">
//               <Sidebar hideLogo={true} containerId="miniSidebar" />
//             </div>

//             {/* Content Area */}
//             <div id="content" className="position-relative h-100 flex-grow-1">
//               <Header />
//               <div className="custom-container">{children}</div>
//               <div className="custom-container">
//                 <span className="me-1">Theme distributed by - </span>
//                 <a
//                   href="https://www.themewagon.com/"
//                   target="_blank"
//                   rel="noopener noreferrer"
//                 >
//                   ThemeWagon
//                 </a>
//               </div>
//             </div>
//           </div> */}
//         </ClientWrapper>
//       </body>
//     </html>
//   );
// }

//import modules libraries
import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";

//import custom components
import ClientWrapper from "components/common/ClientWrapper";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

// import main theme scss
import "styles/theme.scss";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientWrapper>
      <html lang="en" className="expanded">
        <body className={`${publicSans.variable}`}>{children}</body>
      </html>
    </ClientWrapper>
  );
}
